#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          jrdsagent
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start jrdsagent at boot time
# Description:       Jrds is performance collector
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin

DESC="JRDS Performance Collector Agent"
NAME=jrdsagent
SCRIPTNAME=/etc/init.d/$NAME
PIDFILE=/var/run/$NAME/jrdsagent.pid
JRDSAGENT_USER=jrds
JRDSAGENT_JAR=/usr/share/jrdsagent/jrdsagent.jar
JRDSAGENT_PORT=2002
JRDSAGENT_PROTO=jmx
JAVA=java

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

DAEMON=/usr/bin/daemon
DAEMON_ARGS="--name=$NAME --inherit --pidfile=$PIDFILE"

SU=/bin/su

[ -x "$DAEMON" ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

# Make sure we run as root
if [ `id -u` -ne 0 ]; then
    echo "The $NAME init script can only be run as root"
    exit 1
fi

#
# Function that starts the daemon/service
#
do_start()
{
    # the default location is /var/run/jrds/jrdsagent.pid but the parent directory might need to be created
    mkdir `dirname $PIDFILE` > /dev/null 2>&1 || true
    chown $JRDSAGENT_USER `dirname $PIDFILE`

    # Return
    #   0 if daemon has been started
    #   1 if daemon was already running
    #   2 if daemon could not be started
    $DAEMON $DAEMON_ARGS --running && return 1

    # If the var MAXOPENFILES is enabled in /etc/default/jrdsagent then set the max open files to the 
    # proper value
    if [ -n "$MAXOPENFILES" ]; then
        [ "$VERBOSE" != no ] && echo Setting up max open files limit to $MAXOPENFILES
        ulimit -n $MAXOPENFILES
    fi
    
    # --user in daemon doesn't prepare environment variables like HOME, USER, LOGNAME or USERNAME,
    # so we let su do so for us now
    $SU -l $JRDSAGENT_USER --shell=/bin/bash -c "$DAEMON $DAEMON_ARGS -- $JAVA $JAVA_ARGS -Djrds.port=$JRDSAGENT_PORT -Djrds.proto=$JRDSAGENT_PROTO -jar $JRDSAGENT_JAR $JRDSAGENT_ARGS" || return 2
}


#
# Verify that all jrds processes have been shutdown
# and if not, then do killall for them
# 
get_running() 
{
    return `ps -U $JRDSAGENT_USER --no-headers -f | egrep -e '(java|daemon)' | grep -c . `
}

force_stop() 
{
    get_running
    if [ $? -ne 0 ]; then 
	killall -u $JRDSAGENT_USER java daemon || return 3
    fi
}

# Get the status of the daemon process
get_daemon_status()
{
    $DAEMON $DAEMON_ARGS --running || return 1
}


#
# Function that stops the daemon/service
#
do_stop()
{
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred
    get_daemon_status 
    case "$?" in
	0) 
	    $DAEMON $DAEMON_ARGS --stop || return 2
        # wait for the process to really terminate
        for n in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
            sleep 1
            $DAEMON $DAEMON_ARGS --running || break
        done
        if get_daemon_status; then
	        force_stop || return 3
        fi
	    ;;
	*)
	    force_stop || return 3
	    ;;
    esac

    # Many daemons don't delete their pidfiles when they exit.
    rm -f $PIDFILE
    return 0
}

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    do_start
    case "$?" in
        0|1) log_end_msg 0 ;;
        2) log_end_msg 1 ;;
    esac
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    do_stop
    case "$?" in
        0|1) log_end_msg 0 ;;
        2) log_end_msg 1 ;;
    esac
    ;;
  restart|force-reload)
    #
    # If the "reload" option is implemented then remove the
    # 'force-reload' alias
    #
    log_daemon_msg "Restarting $DESC" "$NAME"
    do_stop
    case "$?" in
      0|1)
        do_start
        case "$?" in
          0) log_end_msg 0 ;;
          1) log_end_msg 1 ;; # Old process is still running
          *) log_end_msg 1 ;; # Failed to start
        esac
        ;;
      *)
  	# Failed to stop
	log_end_msg 1
	;;
    esac
    ;;
  status)
	get_daemon_status
	case "$?" in 
	 0) 
		echo "$DESC is running with the pid `cat $PIDFILE`"
		rc=0
		;;
	*) 
		get_running
		procs=$?
		if [ $procs -eq 0 ]; then 
			echo -n "$DESC is not running"
			if [ -f $PIDFILE ]; then 
				echo ", but the pidfile ($PIDFILE) still exists"
				rc=1
			else 
				echo
				rc=3
			fi
		
		else 
			echo "$procs instances of jrds are running at the moment"
			echo "but the pidfile $PIDFILE is missing"
			rc=0
		fi
		
		exit $rc
		;;
	esac
	;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
    exit 3
    ;;
esac

exit 0
